name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi
          pip install -e ".[ci]" || pip install -e .

      - name: Test
        env:
          PYTEST_ADDOPTS: --override-ini addopts=
        run: pytest -q
