name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Use minimal CI requirements (no heavy ML deps)
          if [ -f requirements-ci.txt ]; then 
            pip install -r requirements-ci.txt
          elif [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          fi
          # Install package in development mode
          if [ -f pyproject.toml ]; then pip install -e .; fi

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          # Run tests with verbose output
          if [ -d tests ]; then 
            pytest tests/ -v
          fi
          if [ -d src/financial_agent/bridge/tests ]; then
            pytest src/financial_agent/bridge/tests/ -v
          fi
          
      - name: Run linting (optional)
        continue-on-error: true
        run: |
          flake8 src/financial_agent --max-line-length=100 --exclude=__pycache__,*.pyc
